[package]
name = "flare"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
anyhow = "1.0"
freedesktop-desktop-entry = "0.7.19"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5.0"
libc = "0.2"
